version: '3.7'
services:
  postgres:
    container_name: autospend-dev-machine-postgres
    image: postgres:16.3-alpine3.20
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=autospend
